### ISSUE TITLE
Checklist: Week of Dec 14

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#101]
### Speakers & Performers
* [x] Get talk description from Jon
* [x] Lock in 4 out of 4 speakers
  * [ ] Reach out to Nicole (@visnup)
  * [x] Find more creative talks (everyone)
* [ ] Lock in 2 out of 2 performers
* [x] More background cafe-like performances (like Evan) (Myles)
* [ ] Ask karaoke-ers to pick shorter, more recognizable songs (@visnup)
* [ ] Reminder to use large high-contrast font for code slides (@visnup)
* [ ] Email TechShop and have them pin up the call for speakers on their community board (@kellyk)
* [ ] Find robotics speakers (@emilyrose)
* [ ] Get alterconf/TechInclusion past speakers (@kellyk)

### Sales & Promotion
* [ ] wafflejs.com/student – photos, student testimonials, promotional stuff (@billyroh)
* [ ] Ask coding schools and universities to help us promote (@kellyk)

### Equipment
* [ ] Pictionary cards (@visnup)
* [ ] Butcher paper (@visnup)
* [ ] Scissors (@visnup)
* [ ] Sharpies
* [ ] Name tags
* [ ] Tupperware container for stickers
* [x] Opendoor stickers
* [ ] Test lapel mic with a PA (@visnup, Brian)
* [ ] Get a bigger carrying case (@visnup)
* [ ] 2x Stereo RCA → 1/4" cables, short (mixer-to-DAC interconnect, mixer-to-barn-soundsystem interconnect) (@visnup)
* [ ] Power cable for PA long enough to have the PA and projector connect to the same extension cable (@visnup)
* [x] Short XLR cables for wireless mic receiver to mixer connections (@visnup)

### Odds & Ends
* [ ] Order a few plain waffles (@billyroh)
* [ ] Visualize repeat attendance (gauge loyalty) (@visnup)
* [ ] Edit host notes for essentials (@visnup, @emilyrose)
* [ ] Tweak short code of conduct for brevity (@visnup, @emilyrose)

**Comment by billyroh** [comment]
:point_right: https://github.com/wafflejs/wafflejs.github.io/issues/102
