### ISSUE TITLE
Checklist: Week of Jan 4

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#107]
### Speakers & Performers
* [ ] Ask karaoke-ers to pick shorter, more recognizable songs (@visnup)
* [ ] Reminder to use large high-contrast font for code slides (@visnup)
* [ ] Email TechShop and have them pin up the call for speakers on their community board (@kellyk)
* [ ] Find robotics speakers (@emilyrose)
* [ ] Get alterconf/TechInclusion past speakers (@kellyk)

### Sales & Promotion
* [ ] wafflejs.com/student – photos, student testimonials, promotional stuff (@billyroh)
* [ ] Ask coding schools and universities to help us promote (@kellyk)

### Equipment
* [ ] Sharpies
* [ ] Name tags
* [ ] Tupperware container for stickers
* [x] Test lapel mic with a PA (@visnup, Brian)
* [ ] Get a bigger carrying case (@visnup)
* [ ] 2x Stereo RCA → 1/4" cables, short (mixer-to-DAC interconnect, mixer-to-barn-soundsystem interconnect) (@visnup)
* [ ] Power cable for PA long enough to have the PA and projector connect to the same extension cable (@visnup)

### Odds & Ends
* [ ] Intro slides + script (@visnup)
  * [ ] Edit host notes for essentials (@visnup, @emilyrose)
  * [ ] Tweak short code of conduct for brevity (@visnup, @emilyrose)
