### ISSUE TITLE
Checklist: Day-of

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#111]
### During the Event
* [ ] Always ask the venue to setup all the TVs (or turned off) (@kellyk)
* [ ] Have everyone introduce themselves at the start (Everyone)
* [ ] Have some sort of group game thing during intermission (@billyroh)

### Equipment
* [x] Microphone stand (optional)
* [x] Butcher paper
* [x] Wagon
  * [x] Microphone case
    * [x] Wired microphones
    * [x] Wireless microphones
    * [x] Microphone body packs
  * [x] Projector
    * [x] Slideshow clicker
    * [x] Headset microphones
    * [x] Displayport to HDMI
  * [x] Projector screen
  * [x] Speaker stands
  * [x] Speakers
  * [x] Blankets x4
  * [x] Crayons
  * [x] Jenga x3
* [ ] Roller bag
  * [x] Audio mixer
  * [x] DAC
  * [x] Cables, Extension cords
  * [x] HDMI switch
  * [ ] Extra Batteries (AA x4, AAA x2)
  * [ ] Gaffer tape
  * [x] Nametags
  * [x] Sharpies
  * [x] Stickers
    * [x] JS
    * [x] CSS
    * [x] Waffle
    * [x] Opendoor
  * [ ] WaffleJS poster
