### ISSUE TITLE
Checklist: Week of Jan 11

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#118]
### Speakers & Performers
* [ ] Bias toward more JavaScript-y speakers (all)
* [ ] Source from the robotics js community (all)
* [ ] Structure future music demos more (???)
    - Just music during intro
    - Thank you + intro after
    - Mention upcoming demo after intermission
    - Start with just music during intermission
    - Segue into time-boxed 5 min explanation/demo at the end
* [ ] Reach out to Nicole (@visnup)
* [ ] Reach out Paul Irish (@visnup)
* [ ] Reach out to Brian Hughes (@visnup)

### Sponsors
* [x] Send Earnest a W-9 (@visnup)
* [ ] Get money from Earnest

### Equipment
* [x] Order headset mic(s) http://www.amazon.com/Shure-Performance-Headset-Condenser-Microphone/dp/B00IVPFZ9W (@visnup)
* [x] 2x 6' extension cords (@visnup)

### Before the Event
* [ ] Email Golden Waffle more ahead of time (@billyroh)
* [ ] Order more plain waffles (@billyroh)

### Odds & Ends
* [x] Get venue invoice for next month (@billyroh)
* [ ] Close out accounting (@visnup)

**Comment by billyroh** [comment]
:point_right: https://github.com/wafflejs/wafflejs.github.io/issues/126
