### ISSUE TITLE
Checklist: Week of Jan 18

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#126]
### Speakers & Performers
* [ ] Bias toward more JavaScript-y speakers (all)
* [ ] Source from the robotics js community (all)
* [ ] Structure future music demos more (???)
    - Just music during intro
    - Thank you + intro after
    - Mention upcoming demo after intermission
    - Start with just music during intermission
    - Segue into time-boxed 5 min explanation/demo at the end
* [ ] Reach out to Nicole (@visnup)
* [x] Reach out Paul Irish (@visnup)
* [ ] Reach out to Brian Hughes (@visnup)

### Sponsors
* [ ] Get money from Earnest

### Before the Event
* [x] Email Golden Waffle more ahead of time (@billyroh)
* [x] Order more plain waffles (@billyroh)

### Odds & Ends
* [ ] Close out accounting (@visnup)

**Comment by billyroh** [comment]
:point_right: https://github.com/wafflejs/wafflejs.github.io/issues/127
