### ISSUE TITLE
Checklist: Week of Jan 25

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#127]
### Speakers & Performers
* [ ] Bias toward more JavaScript-y speakers (all)
* [ ] Source from the robotics js community (all)
* [ ] Reach out to Nicole (@visnup)
* [ ] Reach out to Brian Hughes (@visnup)

### Sponsors
* [ ] Get money from Earnest

### Odds & Ends
* [ ] Close out accounting (@visnup)

**Comment by billyroh** [comment]
:point_right: https://github.com/wafflejs/wafflejs.github.io/issues/128
