### ISSUE TITLE
Checklist: Week of Feb 1

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#128]
### Speakers & Performers
* [ ] Bias toward more JavaScript-y speakers (all)
* [ ] Source from the robotics js community (all)
* [ ] Reach out to Nicole (@visnup)
* [ ] Reach out to Brian Hughes (@visnup)

### Sponsors
* [x] Get money from Earnest

### Odds & Ends
* [x] Close out accounting for January (@visnup)
