### ISSUE TITLE
Checklist: Post-Event

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#129]
* [x] Create a new ti.to event for the new month
* [x] Update attendance stats
* [x] Send email to attendees that includes:
  * [x] Survey
  * [x] Link to call for speakers, performers
  * [x] Link to purchase tickets
* [x] Tweet out link to survey
* [x] Retro (working, not working, how)
* [x] Get venue invoice for next month
* [ ] Close out accounting for previous month
* [ ] Throw out unnecessary cables

### Reorder
* [x] JS/CSS Stickers
* [x] Butcher paper
