### ISSUE TITLE
Pre-event Checklist

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#44]
* [x] Jetpack for internet (Visnu's getting this from Erica)
* [x] Email attendees day before event (Billy/Visnu)
* [ ] Intro notes (Billy/Visnu)
  - welcome
  - first Wednesdays
  - code of conduct
  - waffle voucher
  - sponsors

* [ ] Speaker intro notes (Visnu)
  - Susan – designer, developer, and illustrator. currently working at treehouse. you may have seen her sketch notes, tree water colors, or her rad stickers.
  - Lunny – Google hangout borojs + Alex sexton
  - contra – beer.js, talks about gulp
  - Aniyia – CEO, founder of tinsel. Set of headphones that double as a fashion forward beautiful necklace. When Aniyia agreed to sing, I felt a little bad for all the other singers.
  - Guillermo – puppy photos
  - Nelson
  - May-Li – lead of mobile and experimental design at khan academy. before this, she worked at apple, designing and prototyping UI and hardware concepts that led to such things as: force touch, taptic engine, face tracking, multi-touch
  - Stephanie, steven - Andrew Lunny will intro

**Comment by billyroh** [comment]
@visnup Do you have speaker intro notes?

**Comment by visnup** [comment]
Intro notes

- welcome
- first Wednesdays
- code of conduct
- waffle
- sponsors

**Comment by visnup** [comment]
@billyroh actually do you want to intro may-li?

**Comment by billyroh** [comment]
Sure! I'd be down to do that

**Comment by billyroh** [comment]
Wrote up some notes here: https://github.com/wafflejs/presentation-notes
