### ISSUE TITLE
Checklist: August 24–30

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#49]
### Speakers & Performers
* [x] Fill 4 out of 4 speaking slots
* [x] Fill 4 out of 4 performing slots
* [x] Confirm with speakers (@billyroh)
* [x] Confirm with performers (@billyroh)
* [x] Get bios for speakers (@billyroh)
    * [Monica](https://gist.githubusercontent.com/billyroh/5110c347d5be683d1f79/raw/f0ff2e55314b685a80364b67ced0208a3e9855fd/monica.txt)
  * [Justine](https://gist.githubusercontent.com/billyroh/fed194bde7ae7b88a13c/raw/0cb6a0f46ba857752a6e38e600a5f9aa211953f8/justine.txt)
  * [Jeanie](https://gist.githubusercontent.com/billyroh/3e5647a92b3555cb7941/raw/b4d0b7a9cb8c5b6c214cc9f4732efe20fa90c563/jeanie.txt)
  * [Isaac](https://gist.githubusercontent.com/billyroh/607fe690b3e41aa86c29/raw/007a9dc6db98f23fa1e4588b2283b32b07f101b7/isaac.txt)
* [x] Get bios for performers (@billyroh)
  * [Natasha](https://gist.githubusercontent.com/billyroh/9f53110adce389e76052/raw/ed1109aeb408fb24592981c20852c4a4f4648743/gistfile1.txt)
  * [Billy](https://gist.githubusercontent.com/billyroh/0d9da9e295c68185f2a3/raw/b3f3163e4e20608f30b7373fd92f3080a00f24b0/billy.txt)
  * [Gabriel](https://gist.githubusercontent.com/billyroh/099e2b0237ed0eaf5c56/raw/e7c29baee83629659ca78ef41439973299e072dc/gabriel.txt)
 
### Sales and Promotion
* [x] Sell 51 out of 51 regular tickets
* [x] Sell 5 out of 5 student sponsorship tickets
* [x] Get upfront money from sponsors (@billyroh)
  * [x] Opendoor (@billyroh)
  * [x] Crunchyroll (@kellyk)
* [x] Ask BrooklynJS peeps to tweet out link (@visnup)

### Logistics
* [x] Do a dry run on August 26 with all A/V equipment
* [x] Build out karaoke catalogue and reservation system (@visnup)
* [x] Task people you know with getting feedback and socializing with others (@visnup, @billyroh, @kellyk)
* [x] Get two A/V people (@visnup)
* [ ] Close out last month's accounting spreadsheet (@visnup)
* [x] Add sponsors to the website (@billyroh)
* [x] Send out reminder email to attendees on Tuesday (@billyroh)

### A/V
* [x] Projector
* [x] Projector screen
* [ ] Extension cord
* [x] HDMI cord
* [ ] Powerstrip
* [x] A thing to connect your computer to the projector
* [x] Microphones
* [x] Microphone stand
* [x] Audio mixer

### Things we forgot
* [ ] 5 Sharpies
* [ ] Print out a "WaffleJS" poster
* [ ] Confirm with Grant re: mics and speakers
* [ ] Extension cord
* [ ] Powerstrip

**Comment by visnup** [comment]
I like the Things We Forgot section
