### ISSUE TITLE
Checklist: Post-Event

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#53]
* [x] Create a call for speakers
* [x] Create a call for performers
* [x] Store the old page somewhere
* [x] Create a new page for the new month
* [x] Create a new ti.to event for the new month
* [x] Send email to attendees that includes:
  * [x] Survey
  * [x] Link to call for speakers, performers
  * [x] Link to purchase tickets
  * [x] Link to becoming a sponsor
* [x] Retro (working, not working, how)

### Reorder

* [ ] Name tags

**Comment by visnup** [comment]
Survey https://wafflejs.typeform.com/to/mfxPYK
