### ISSUE TITLE
Checklist: Sept 3–6

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#55]
### Logistics
* [x] Reduced barn pricing (@billyroh)
* [ ] Other venues (@billyroh)
* [ ] Put up tickets for sale
* [ ] Get one speaker
* [ ] Hackbright

### Buy
* [ ] Name tags (@billyroh)
* [ ] Stickers (@visnup)
* [ ] Wireless mics (@visnup)
* [x] Wired mic (@visnup)
