### ISSUE TITLE
Checklist: Sept 7–13

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#56]
### Logistics
* [x] Reduced barn pricing (@billyroh)
* [x] Investigate other venues (@billyroh)
* [x] Get one speaker
* [ ] Reach out to Crunchyroll about sponsorship (@kellyk)
* [x] Get sponsorship from Opendoor (@billyroh)
* [ ] Put down $550 for waffle truck (@visnup)
* [ ] Find a performer (@visnup)
  * [ ] Confirm with SSF re: full band (@visnup)
* [ ] Really close out accounting for August, September (@visnup)
* [ ] Tweet out how much we made from August, September (@visnup)

### Sales & Promotion
* [x] Put up tickets for sale (@billyroh)
* [x] Reach out to dev schools (5 tickets) (@kellyk)
  * [ ] Reach out to Hackbright (5 tickets) (@visnup)
* [x] Tweet out link to call for speakers (@billyroh)

### Buy
* [ ] Name tags (@billyroh)
* [ ] Stickers (@visnup)
* [ ] Wireless mics (@visnup)
* [x] Wired mic (@visnup)

**Comment by billyroh** [comment]
Moved over incomplete tasks here: https://github.com/wafflejs/wafflejs.github.io/issues/57
