### ISSUE TITLE
Checklist: Sept 14–20

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#57]
### Speakers & Performers
* [x] Fill 1 of 2 performer slots (@visnup)
* [x] Fill 3 of 4 speaker slots

### Logistics
* [ ] Get one more sponsor
  * [x] Reach out to Crunchyroll about sponsorship (@kellyk)
  * [x] Reach out to Stripe about sponsorship (@billyroh)
* [ ] Put down $550 for waffle truck (@visnup)
* [x] Reach out to Hackbright (5 tickets) (@visnup)
* [x] Really close out accounting for August, September (@visnup)
  * [x] Collect August sponsorship money (@visnup)
  * [x] Tweet out how much we're donating from August, September (@visnup)

### Sales & Promotion
* [x] Sell 30 of 30 early bird tickets
* [ ] Sell 30 of 100 regular tickets

### Odds & Ends
* [ ] Name tags (@billyroh)
* [x] Stickers (@visnup)
* [x] Buttons (@visnup)
* [ ] Wireless mics (@visnup)
* [ ] Slideshow clicker (@kellyk)

**Comment by visnup** [comment]
can we get away with an apple remote as the slideshow clicker?

**Comment by kellyk** [comment]
I have an extra clicker!

**Comment by billyroh** [comment]
Moved incomplete tasks here: https://github.com/wafflejs/wafflejs.github.io/issues/58
