### ISSUE TITLE
Checklist: Sept 21–27

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#58]
### Sponsorship
* [x] Sponsorship prospectus (@billyroh)
* [ ] Email old node knockout sponsors (@visnup)
* [x] Reach out to New Relic (@visnup)
* [x] Reach out to npm (@visnup)
* [x] Email attendees about sponsorship + other stuff (@billyroh)

### Logistics
* [x] Put down $550 for waffle truck (@visnup)
* [x] Get a photographer

### Sales & Promotion
* [ ] Sell 50 of 100 regular tickets
* [ ] Get 10 of 10 people on the student waitlist

### Odds & Ends
* [x] Name tags (@billyroh)
* [ ] Wireless mics (@visnup)
* [x] Slideshow clicker (@kellyk)

**Comment by visnup** [comment]
I'm holding off on the wireless mics until accounting shows we'll have money to buy them with (either getting another sponsor or selling 100 regular tickets).

**Comment by billyroh** [comment]
Moved incomplete tasks here: https://github.com/wafflejs/wafflejs.github.io/issues/59
