### ISSUE TITLE
Checklist: Sept 28–Oct 4

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#59]
### Sponsorship
* [ ] Get a sponsor!
* [ ] Email old node knockout sponsors (@visnup)
* [ ] Reach out to...
  * [x] Slack (@billyroh)
  * [x] Tito (@billyroh)
  * [x] Clara (@billyroh)
  * [x] npm (@visnup)
  * [ ] CircleCI (@visnup)
  * [x] IBM (@visnup)
  * [ ] Modulus (@visnup)

### Sales & Promotion
* [ ] Sell 80 of 100 regular tickets
* [x] Get 10 of 10 people on the student waitlist
* [x] Get speakers to help promote (@billyroh)
* [ ] Get friends and acquaintances to buy tickets
* [x] Get Opendoor to buy a bunch of tickets and distribute them (@billyroh)
* [x] Go to other meetups and get people to come to WaffleJS
  * [x] DogpatchJS (@visnup)
  * [x] GitHub Universe (@visnup)

### Odds & Ends
* [x] A/V dry run
* [ ] Update waffle order?
* [ ] Wireless mics (@visnup)

**Comment by visnup** [comment]
@billyroh how many waffles does the initial order get us? will we need to update to a larger number than usual?

**Comment by billyroh** [comment]
It gets us 78 waffles. We had leftover waffles last time, so I don't think
we'll need more than 78.

**Comment by visnup** [comment]
whoops, didn't read your comment until just now. I just emailed Grant about how to up our order. I guess we don't have to confirm we want to do it until later...

**Comment by billyroh** [comment]
Moved incomplete items over here: https://github.com/wafflejs/wafflejs.github.io/issues/59
