### ISSUE TITLE
Checklist: October 5–7

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#60]
### Sponsorship
* [ ] Get a sponsor!
* [ ] Email old node knockout sponsors (@visnup)
* [ ] Reach out to...
  * [ ] CircleCI (@visnup)
  * [ ] Modulus (@visnup)

### Speakers & Performers
* [x] Confirm with speakers (@billyroh)
* [x] Confirm with performers (@billyroh)
* [x] Get bios for speakers (@billyroh)

### Sales & Promotion
* [x] 10 of 10 Students
* [x] Sell 80 of 100 regular tickets
* [x] Get friends and acquaintances to buy tickets
* [x] Send out reminder email to attendees on Tuesday (@billyroh)

### Odds & Ends
* [x] Task people you know with getting feedback and socializing with others (@visnup, @billyroh)
* [x] Update waffle order
* [ ] Wireless mics (@visnup)
* [ ] Pitch the sponsorship during intro (@visnup, @emilyrose)
* [ ] Test clicker (@visnup)
* [ ] Make FAQ for speakers (@billyroh)

### Equipment
* [ ] Projector
* [ ] Projector screen
* [ ] Extension cord
* [ ] Powerstrip
* [ ] HDMI cord(s)
* [ ] HDMI adapters
* [ ] Microphones
* [ ] Microphone stand
* [ ] Audio mixer
* [ ] 5 Sharpies
* [ ] Confirm with Grant re: mics and speakers
