### ISSUE TITLE
Checklist: Post-Event

### ISSUE THREAD

**Issue by visnup** [wafflejs/wafflejs.github.io#61]
* [x] Create a call for speakers
* [x] Create a call for performers
* [x] Store the old page somewhere
* [x] Create a new page for the new month
* [x] Create a new ti.to event for the new month
* [x] Send email to attendees that includes:
  * [x] Survey
  * [x] Link to call for speakers, performers
  * [x] Link to purchase tickets
  * [x] Link to becoming a sponsor
* [x] Tweet out link to survey
* [x] Retro (working, not working, how)

### Reorder

* [ ] Name tags

### Turns out we need

* [ ] Wireless mics
* [ ] More audio adapters
