### ISSUE TITLE
Checklist: Day-of

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#65]
### A/V
* [x] Slideshow clicker
* [x] Slideshow clicker batteries
* [x] Wired microphones
* [x] Wireless microphones
* [x] Audio mixer
* [ ] 3 x Extension cords
* [x] Displayport to HDMI
* [x] Projector
* [x] Projector screen

### Check-in desk
* [x] Nametags
* [x] Sharpies
* [x] Stickers
  * [x] JS
  * [x] CSS
  * [x] Waffle
* [x] WaffleJS poster
* [x] Waffle vouchers
* [x] Gaffer tape

### Odds & Ends
* [x] Pitch the sponsorship during intro (@visnup, @emilyrose)
* [x] Test clicker (@visnup)
* [ ] Make FAQ for speakers (@billyroh)
