### ISSUE TITLE
Checklist: Oct 8–11

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#71]
### Sponsorship
* [ ] Particle (@emilyrose)
* [ ] Dropbox (@billyroh)
* [ ] Clef (@billyroh)

### Speakers & Performers
* [ ] Reach out to Aniyia (@visnup)
* [x] Reach out to Marco (@visnup)
* [x] Reach out to Rockbot (@emilyrose)
* [ ] Reach out to Zach (@billyroh)
* [ ] Create an FAQ page for speakers (@billyroh)

### Sales & Promotion
* [ ] Reach out to dev/color (@kellyk)
* [ ] Reach out to Telegraph Academy (@kellyk)

### A/V
* [ ] Use the TVs on the walls (everyone)
* [ ] Wireless microphone

### Odds & Ends
* [ ] Order more nutella waffles (@billyroh)
* [ ] Buy blankets to sit on (@billyroh)
* [ ] Make the survey before the event (@visnup)
* [ ] Make a staff sticker so people know who's who (@billyroh)

**Comment by visnup** [comment]
moved "Actual Event" stuff to #72.

**Comment by billyroh** [comment]
:point_right: https://github.com/wafflejs/wafflejs.github.io/issues/74
