### ISSUE TITLE
Checklist: Day-of

### ISSUE THREAD

**Issue by visnup** [wafflejs/wafflejs.github.io#72]
### A/V
* [ ] Slideshow clicker
* [ ] Slideshow clicker batteries
* [ ] Wired microphones
* [ ] Wireless microphones
* [ ] Audio mixer
* [ ] 3 x Extension cords
* [ ] Displayport to HDMI
* [ ] Projector
* [ ] Projector screen
* [ ] Batteries
* [ ] Extension cords

### Check-in desk
* [ ] Nametags
* [ ] Sharpies
* [ ] Stickers
  * [ ] JS
  * [ ] CSS
  * [ ] Waffle
* [ ] WaffleJS poster
* [ ] Waffle vouchers
* [ ] Gaffer tape
* [ ] Name tag poster

### Odds & Ends
* [ ] Get caffeinated and mentally prepared before event (@emilyrose, @visnup)
* [ ] Distribute stickers, name tags, pens to each table, in addition to the central check-in area (@billyroh)
* [ ] Have a single area for waffles on the side (@billyroh)
* [ ] Have two people do check-in (@billyroh)
* [ ] Talk about the karaoke sign up page at each stage (@emilyrose, @visnup)
* [ ] Write in email: parking is tough in the area. don’t drive. (@billyroh)

**Comment by visnup** [comment]
moved some intro stuff to #73.
