### ISSUE TITLE
Checklist: Oct 12–18

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#74]
### Logistics
* [ ] Reserve barn (@billyroh, @visnup)

### Sponsorship
* [ ] Particle (@emilyrose)
* [x] Dropbox (@billyroh)
* [x] Clef (@billyroh)

### Speakers & Performers
* [ ] Reach out to Aniyia (@visnup)
* [x] Reach out to Zach (@billyroh)
* [ ] Create an FAQ page for speakers (@billyroh)

### Sales & Promotion
* [x] Reach out to dev/color (@kellyk)
* [ ] Reach out to Telegraph Academy (@kellyk)

### A/V
* [ ] Use the TVs on the walls (everyone)
* [ ] Wireless microphone

### Odds & Ends
* [ ] Order [tambourines](http://www.amazon.com/YMC-TAM20-BLACK-Double-Row-Tambourine/dp/B0002F5C7Y) (@visnup)
* [ ] Order [butcher paper](http://www.amazon.com/Spectra-ArtKraft-Duo-Finish-67004-Heavyweight/dp/B00006IE0U) for tables (@visnup)
* [ ] Order [crayons](http://www.amazon.com/Crayola-Ultimate-Crayon-Case-152-Crayons/dp/B00CI6J3HA/) for tables (@visnup)
* [ ] Order card games for tables (@visnup)
* [ ] Order more nutella waffles (@billyroh)
* [ ] Buy blankets to sit on (@billyroh)
* [ ] Make the survey before the event (@visnup)
* [ ] Make a staff sticker so people know who's who (@billyroh)

**Comment by billyroh** [comment]
:point_right: https://github.com/wafflejs/wafflejs.github.io/issues/75
