### ISSUE TITLE
Checklist: Oct 19–25

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#75]
### Logistics
* [x] Reserve barn (@billyroh, @visnup)

### Sponsorship
* [x] Particle (@emilyrose)
* [ ] Get money from Opendoor (@visnup)

### Speakers & Performers
* [ ] Lock down 2 of 4 speakers
* [ ] Lock down 2 of 2 performers
* [ ] Reach out to Aniyia (@visnup)
* [ ] Reach out to Mariko (@visnup)
* [ ] Reach out to Nicole Sullivan (@visnup)
* [ ] Reach out to Raquel (@visnup)
* [ ] Reach out to substack (@visnup)
* [ ] Reach out to node people (@visnup)
* [ ] Create an FAQ page for speakers (@billyroh)
* [ ] Confirm with Clay re: performance (@visnup)
* [ ] Confirm with Maria re: performance (@visnup)
* [ ] Reach out to Ash (@kellyk)
* [ ] Reach out to Fiona (@kellyk)
* [ ] Reach out to Michael North (@kellyk)
* [ ] Reach out to Marina (@kellyk)
* [ ] Source from the Airbnb eng event (@kellyk)
* [ ] Ask past speakers for referrals

### Sales & Promotion
* [ ] Reach out to Telegraph Academy (@kellyk)
* [x] Sell 20 of 20 early bird tickets
* [ ] Sell 30 of 100 regular tickets

### A/V
* [ ] Use the TVs on the walls (everyone)
* [x] Wireless microphone

### Odds & Ends
* [ ] Order [tambourines](http://www.amazon.com/YMC-TAM20-BLACK-Double-Row-Tambourine/dp/B0002F5C7Y) (@visnup)
* [ ] Order [butcher paper](http://www.amazon.com/Spectra-ArtKraft-Duo-Finish-67004-Heavyweight/dp/B00006IE0U) for tables (@visnup)
* [ ] Order [crayons](http://www.amazon.com/Crayola-Ultimate-Crayon-Case-152-Crayons/dp/B00CI6J3HA/) for tables (@visnup)
* [ ] Order card games for tables (@visnup)
* [ ] Order more nutella waffles (@billyroh)
* [ ] Buy blankets to sit on (@billyroh)
* [ ] Make the survey before the event (@visnup)
* [ ] Make a staff sticker so people know who's who (@billyroh)

**Comment by billyroh** [comment]
:point_right: https://github.com/wafflejs/wafflejs.github.io/issues/77
