### ISSUE TITLE
Checklist: Oct 26–Nov 1

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#77]
### Sponsorship
* [ ] Get money from Opendoor (@visnup)

### Speakers & Performers
* [x] Lock down 4 of 4 speakers
* [ ] Lock down 3 of 3 performers
* [ ] Reach out to Aniyia (@visnup)
* [x] Reach out to Mariko (@visnup)
* [x] Reach out to Nicole Sullivan (@visnup)
* [x] Reach out to Raquel (@visnup)
* [ ] Reach out to substack (@visnup)
* [x] Reach out to node people (@visnup)
* [x] Create an FAQ page for speakers (@billyroh)
* [x] Confirm with Evan re: performance (@visnup)
* [x] Confirm with Maria re: performance (@visnup)
* [x] Reach out to Ash (@kellyk)
* [x] Reach out to Fiona (@kellyk)
* [x] Reach out to Michael North (@kellyk)
* [x] Reach out to Marina (@kellyk)
* [ ] Source from the Airbnb eng event (@kellyk)
* [ ] Ask past speakers for referrals

### Sales & Promotion
* [x] Reach out to Telegraph Academy (@kellyk)
* [x] Sell 80 of 100 regular tickets

### A/V
* [ ] Use the TVs on the walls (everyone)

### Odds & Ends
* [x] Order [tambourines](http://www.amazon.com/YMC-TAM20-BLACK-Double-Row-Tambourine/dp/B0002F5C7Y) (@visnup)
* [x] Order [butcher paper](http://www.amazon.com/Spectra-ArtKraft-Duo-Finish-67004-Heavyweight/dp/B00006IE0U) for tables (@visnup)
* [x] Order [crayons](http://www.amazon.com/Crayola-Ultimate-Crayon-Case-152-Crayons/dp/B00CI6J3HA/) for tables (@visnup)
* [x] Order card games for tables (@visnup)
* [ ] Order more nutella waffles (@billyroh)
* [x] Buy blankets to sit on (@visnup)
* [ ] Make the survey before the event (@visnup)
* [ ] Make a staff sticker so people know who's who (@billyroh)

**Comment by billyroh** [comment]
:point_right: https://github.com/wafflejs/wafflejs.github.io/issues/79
