### ISSUE TITLE
Checklist: Nov 2–4

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#79]
### Sponsorship
* [x] Get money from Opendoor (@visnup)

### Sales & Promotion
* [x] Sell 100 of 100 regular tickets

### A/V
* [ ] Use the TVs on the walls (everyone)

### Odds & Ends
* [x] Order more nutella waffles (@billyroh)
* [x] Make the survey before the event (@visnup)
* [ ] Make a staff sticker so people know who's who (@billyroh)

### Equipment
* [ ] Projector
* [ ] Projector screen
* [ ] Extension cords
* [ ] Powerstrips
* [ ] HDMI cord(s)
* [ ] HDMI adapters
* [ ] Microphones
* [ ] Microphone stand
* [ ] Audio mixer
* [ ] Presentation clicker

### Tables
* [ ] Name tags
* [ ] Stickers
* [ ] 5 Sharpies
* [ ] Blankets
* [ ] Games
