### ISSUE TITLE
Checklist: Post-Event

### ISSUE THREAD

**Issue by visnup** [wafflejs/wafflejs.github.io#81]
* [x] Create a call for speakers
* [x] Create a call for performers
* [x] Store the old page somewhere
* [x] Create a new page for the new month
* [x] Create a new ti.to event for the new month
* [x] Update speaker FAQ dates
* [ ] Update sponsorship page stats
* [x] Send email to attendees that includes:
  * [x] Survey
  * [x] Link to call for speakers, performers
  * [x] Link to purchase tickets
  * [x] Link to becoming a sponsor
* [x] Tweet out link to survey
* [x] Retro (working, not working, how)

### Reorder

* [x] Stickers
* [ ] Name tags

### Turns out we need

* [ ] Extension cords
* [ ] Power strips
* [ ] SPDIF to RCA
* [ ] More games?

**Comment by visnup** [comment]
moving the remaining stuff to #82
