### ISSUE TITLE
Checklist: Week of Nov 2

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#82]
### Sponsorship
* [ ] Particle (@emilyrose)
* [x] Dropbox (@billyroh)

### Speakers & Performers
* [x] Reach out to Raquel Velez (@visnup)
* [x] Reach out to Myles Borins (@visnup)
* [x] Reach out to Shirley Wu (@visnup)
* [x] Reach out to Victor Powell (@visnup)
* [x] Reach out to Charlie Robbins (@visnup)
* [ ] Reach out to Marco Rogers (@visnup)
* [x] Reach out to Jon Kuperman (@kellyk)
* [ ] Reach out to Marina (@kellyk)
* [ ] Reach out to Tess (@kellyk)
* [ ] Reach out to Ash (@kellyk)
* [ ] Reach out to Georgia Andrews (@kellyk)
* [ ] Reach out to anyharder (@kellyk)

### Sales & Promotion
* [ ] Reach out to dev/color (@kellyk)
* [ ] Reach out to Telegraph Academy (@kellyk)
* [ ] wafflejs.com/student – photos, student testimonials, promotional stuff (@billyroh)
* [ ] Ask coding schools and universities to help us promote (@kellyk)

### Equipment
* [ ] Get another roller bag thing (@visnup)
* [ ] Get plastic bags for jenga, crayons (@billyroh)
* [ ] Get name tags (@visnup)
* [ ] Get a [SPDIF to RCA thing](http://www.amazon.com/Orei-DA21-Optical-Converter-Headphone/dp/B008EPW7TA ) (@visnup)
* [ ] Buy a speaker stand (@visnup)
* [ ] Get another PA (@visnup)
* [ ] Get quieter table games (@billyroh)
* [ ] Get more gaffer tape (@visnup)
* [ ] 2x extension cords (@visnup)
* [ ] 1x power strip (@visnup)

### Odds & Ends
* [ ] Have some sort of group game thing during intermission (@billyroh)
* [ ] Show karaoke queue on TV (@visnup)
* [ ] Make @wafflejs more like @horse_js, or essential and entertaining (Everyone)
* [ ] Add general intro slides (@visnup)
* [ ] Include a mention of responsible drinking during code of conduct section (@visnup, @emilyrose)

**Comment by billyroh** [comment]
:point_right: https://github.com/wafflejs/wafflejs.github.io/issues/84
