### ISSUE TITLE
Checklist: Day-of

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#83]
### During the Event
* [ ] Have everyone introduce themselves at the start (Everyone)
* [ ] Stop touching the A/V during karaoke (Brian)
* [ ] Mention karaoke after each talk (@visnup, @emilyrose)
* [ ] Have some sort of group game thing during intermission (@billyroh)
* [ ] Show karaoke queue on TV (@visnup)
* [x] Add general intro slides (@visnup)
* [x] Include a mention of responsible drinking during code of conduct section (@visnup, @emilyrose)

### Odds and Ends
* [x] Get there in the morning and have a co-working sesh (@visnup)

### A/V
* [x] Slideshow clicker
* [ ] Slideshow clicker batteries
* [x] Wired microphones
* [x] Wireless microphones
* [x] Audio mixer
* [x] 3 x Extension cords
* [x] Displayport to HDMI
* [x] Projector
* [x] Projector screen
* [ ] Batteries

### Check-in desk
* [x] Nametags
* [x] Sharpies
* [x] Stickers
  * [x] JS
  * [x] CSS
  * [x] Waffle
* [x] WaffleJS poster
* [x] Gaffer tape

### Odds & Ends
* [ ] Pitch the sponsorship during intro (@visnup, @emilyrose)
* [ ] Test clicker (@visnup)

**Comment by TheAlphaNerd** [comment]
co working before is a great idea

**Comment by visnup** [comment]
Stole it from @jed

**Comment by visnup** [comment]
@TheAlphaNerd going to be showing up at around 2:30 tomorrow if you want to join

**Comment by TheAlphaNerd** [comment]
sounds delicious :smile:

**Comment by TheAlphaNerd** [comment]
let me know if you want to carpool

**Comment by visnup** [comment]
going to be coming from Opendoor, so nah (unless you want to pick me and a bunch of gear up) :smile:
