### ISSUE TITLE
Checklist: Week of Nov 9

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#84]
### Sponsorship
* [x] Particle (@emilyrose)
* [x] Respond to New Relic (@billyroh)

### Speakers & Performers
* [ ] Lock down 3 of 4 speakers
* [ ] Lock down 2 of 2 performers
* [ ] Reach out to Marco Rogers (@visnup)
* [x] Reach out to Marina (@kellyk)
* [ ] Reach out to Tess (@kellyk)
* [ ] Reach out to Ash (@kellyk)
* [x] Reach out to Georgia Andrews (@kellyk)
* [ ] Reach out to anyharder (@kellyk)
* [ ] Reach out to Shirley re: creative talk (@visnup)
* [ ] Confirm with Myles (@visnup)
* [x] Confirm with Raquel (@visnup)
* [x] Reach out to Jon re: node celebrity game (@kellyk)

### Sales & Promotion
* [ ] Sell 20 of 20 early bird tickets
* [ ] Sell 20 of 100 regular bird tickets
* [ ] Reach out to dev/color (@kellyk)
* [ ] Reach out to Telegraph Academy (@kellyk)
* [ ] wafflejs.com/student – photos, student testimonials, promotional stuff (@billyroh)
* [ ] Ask coding schools and universities to help us promote (@kellyk)

### Equipment
* [ ] Get another roller bag thing (@visnup)
* [ ] Get plastic bags for jenga, crayons (@billyroh)
* [ ] Get name tags (@visnup)
* [ ] Get a [SPDIF to RCA thing](http://www.amazon.com/Orei-DA21-Optical-Converter-Headphone/dp/B008EPW7TA ) (@visnup)
* [ ] Buy a speaker stand (@visnup)
* [ ] Get another PA (@visnup)
* [ ] Get quieter table games (@billyroh)
* [ ] Get more gaffer tape (@visnup)
* [x] 2x extension cords (@visnup)
* [x] 1x power strip (@visnup)

### Odds & Ends
* [ ] Have some sort of group game thing during intermission (@billyroh)
* [ ] Show karaoke queue on TV (@visnup)
* [ ] Make @wafflejs more like @horse_js, or essential and entertaining (Everyone)
* [ ] Add general intro slides (@visnup)
* [ ] Include a mention of responsible drinking during code of conduct section (@visnup, @emilyrose)

**Comment by billyroh** [comment]
:point_right: https://github.com/wafflejs/wafflejs.github.io/issues/85
