### ISSUE TITLE
Checklist: Week of Nov 16

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#85]
### Sponsorship
* [x] Confirm with New Relic (@billyroh)
* [x] Get payment from New Relic (@billyroh)
* [x] Add Opendoor to the site (@billyroh)

### Speakers & Performers
* [x] Lock down 4 of 4 speakers
* [ ] Lock down 2 of 2 performers
* [x] Reach out to Marco Rogers (@visnup)
* [x] Reach out to Tess (@kellyk)
* [x] Reach out to Shirley re: creative talk (@visnup)
* [x] Confirm with Myles (@visnup)
* [ ] Clean up speaker spreadsheet (@billyroh)
* [ ] Add Shirley to the site (@visnup)

### Sales & Promotion
* [x] Sell 20 of 20 early bird tickets
* [ ] Sell 50 of 100 regular bird tickets
* [ ] Reach out to dev/color (@kellyk)
* [ ] Reach out to Telegraph Academy (@kellyk)
* [ ] wafflejs.com/student – photos, student testimonials, promotional stuff (@billyroh)
* [ ] Ask coding schools and universities to help us promote (@kellyk)

### Equipment
* [ ] Get another roller bag thing (@visnup)
* [ ] Get plastic bags for jenga, crayons (@billyroh)
* [x] Get name tags (@visnup)
* [x] Get a [SPDIF to RCA thing](http://www.amazon.com/Orei-DA21-Optical-Converter-Headphone/dp/B008EPW7TA ) (@visnup)
* [x] Buy a speaker stand (@visnup)
* [ ] Get another PA (@visnup)
* [ ] Get quieter table games (@billyroh)
* [x] Get more gaffer tape (@visnup)

### Odds & Ends
* [ ] Have some sort of group game thing during intermission (@billyroh)
* [ ] Show karaoke queue on TV (@visnup)
* [ ] Make @wafflejs more like @horse_js, or essential and entertaining (Everyone)
* [ ] Add general intro slides (@visnup)
* [ ] Include a mention of responsible drinking during code of conduct section (@visnup, @emilyrose)

**Comment by TheAlphaNerd** [comment]
I'm confirmed :p

**Comment by kellyk** [comment]
Re: students, we discussed some kind of buddy system with their sponsor or another attendee

**Comment by billyroh** [comment]
:point_right: https://github.com/wafflejs/wafflejs.github.io/issues/86
