### ISSUE TITLE
Checklist: Week of Nov 23

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#86]
### Speakers & Performers
* [ ] Lock down 2 of 2 performers
* [x] Clean up speaker spreadsheet (@billyroh)
* [x] Add Shirley to the site (@visnup)
* [x] Reach out to Zach (@billyroh)
* [ ] Reach out to Nicole (@visnup)
* [ ] Reach out to Michelle (@billyroh)
* [ ] Reach out to Ge (@visnup)

### Sales & Promotion
* [ ] Sell 80 of 100 regular bird tickets
* [ ] Reach out to dev/color (@kellyk)
* [ ] Reach out to Telegraph Academy (@kellyk)
* [ ] wafflejs.com/student – photos, student testimonials, promotional stuff (@billyroh)
* [ ] Ask coding schools and universities to help us promote (@kellyk)

### Equipment
* [x] Get another roller bag thing (@visnup)
* [ ] Get plastic bags for jenga, crayons (@billyroh)
* [ ] Get another PA (@visnup)
* [ ] Get quieter table games (Pictionary?) (@billyroh)
* [ ] Get 2x lapel mics (@visnup)

### Odds & Ends
* [ ] Have some sort of group game thing during intermission (@billyroh)
* [ ] Show karaoke queue on TV (@visnup)
* [ ] Make @wafflejs more like @horse_js, or essential and entertaining (Everyone)
* [ ] Add general intro slides (@visnup)
* [ ] Include a mention of responsible drinking during code of conduct section (@visnup, @emilyrose)

**Comment by billyroh** [comment]
:point_right: https://github.com/wafflejs/wafflejs.github.io/issues/86
