### ISSUE TITLE
Checklist: Week of Nov 30

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#87]
### Speakers & Performers
* [x] Lock down 2 of 2 performers
* [ ] Reach out to Nicole (@visnup)
* [ ] Reach out to Michelle (@billyroh)
* [x] Reach out to Ge (@visnup)
* [ ] Find more creative talks (everyone)
* [x] Email Jon (@visnup)

### Sales & Promotion
* [ ] Sell 100 of 100 regular bird tickets
* [x] Reach out to dev/color (@kellyk)
* [x] Reach out to Telegraph Academy (@kellyk)
* [ ] Send students a reminder email (@kellyk)
  * WaffleJS is tomorrow!
  * We have a few more available, invite your friends
  * If you can't make it, reply to unregister so someone can take your spot
* [ ] wafflejs.com/student – photos, student testimonials, promotional stuff (@billyroh)
* [ ] Ask coding schools and universities to help us promote (@kellyk)

### Equipment
* [x] Get plastic bags for jenga, crayons (@billyroh)
* [ ] Get another PA (@visnup)
* [ ] Get quieter table games (Pictionary?) (@billyroh)
* [x] Get 2x lapel mics (@visnup)

### Odds & Ends
* [x] Make @wafflejs more like @horse_js, or essential and entertaining (Everyone)
