### ISSUE TITLE
Checklist: Week of Dec 3

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#91]
### Speakers & Performers
* [x] Lock in 1 out of 4 speakers
  * [ ] Reach out to Nicole (@visnup)
  * [x] Reach out to Michelle (@billyroh)
  * [ ] Find more creative talks (everyone)
* [ ] Lock in 1 out of 2 performers
  * [ ] Reach out to Sahana (@visnup)

### Sales & Promotion
* [ ] wafflejs.com/student – photos, student testimonials, promotional stuff (@billyroh)
* [ ] Ask coding schools and universities to help us promote (@kellyk)
* [ ] Ship the new version of the website (@visnup + @billyroh)
* [ ] Get feedback on the idea of a speaker+sponsor brunch to speakers (@visnup + everyone)

### Navel gazing
* [ ] Visualize repeat attendance (gauge loyalty) (@visnup)

### Equipment
* [ ] Get quieter table games (Pictionary?) (@visnup)
* [ ] Order more butcher paper (@visnup)
* [ ] Get scissors (@visnup)
* [ ] Get more sharpies
* [ ] Get tupperware container for stickers
* [ ] Get more Opendoor stickers

**Comment by visnup** [comment]
Jon is already confirmed for Jan.

**Comment by visnup** [comment]
ohh scissors is a good call

**Comment by billyroh** [comment]
:point_right: https://github.com/wafflejs/wafflejs.github.io/issues/96
