### ISSUE TITLE
Checklist: Post-Event

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#92]
* [x] Create a call for speakers
* [x] Create a call for performers
* [x] Store the old page somewhere
* [x] Create a new page for the new month
* [x] Create a new ti.to event for the new month
* [x] Update speaker FAQ dates
* [x] Update sponsorship page stats
* [x] Send email to attendees that includes:
  * [x] Survey
  * [x] Link to call for speakers, performers
  * [x] Link to purchase tickets
  * [x] Link to becoming a sponsor
* [x] Tweet out link to survey
* [x] Retro (working, not working, how)
* [x] Get venue invoice for next month

### Reorder

* [ ] Stickers
* [ ] Name tags
* [ ] Butcher paper

### Turns out we need

* [ ] More games?

**Comment by visnup** [comment]
moved the rest to #96
