### ISSUE TITLE
Checklist: Day-of

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#95]
### During the Event
* [ ] Have everyone introduce themselves at the start (Everyone)
* [ ] Mention karaoke after each talk (@visnup, @emilyrose)
* [ ] Have some sort of group game thing during intermission (@billyroh)
* [ ] Show karaoke queue on TV (@visnup)
* [ ] Add general intro slides (@visnup)
* [ ] Always ask the venue to setup all the TVs (or turned off) (@kellyk)
* [x] Ask people to pick up after themselves in the farewell (@visnup)
* [ ] Raise your hand if you’re hiring; raise your hand if you’re “hirable” (@visnup)
* [x] MCs point out: “if you see an empty seat, standing rule is you can take it. and say hi to your neighbor.” (@visnup)

### A/V
* [x] Slideshow clicker
* [x] Wired microphones
* [x] Wireless microphones
* [x] Audio mixer
* [x] Cables, Extension cords
* [x] Displayport to HDMI
* [x] Projector
* [x] Projector screen
* [x] HDMI switch
* [ ] Batteries (AA, AAA)

### Check-in desk
* [x] Nametags
* [x] Sharpies
* [x] Stickers
  * [ ] JS
  * [ ] CSS
  * [ ] Waffle
  * [ ] Opendoor
* [x] WaffleJS poster
* [x] Gaffer tape

### Odds & Ends
* [ ] Pitch the sponsorship during intro (@visnup, @emilyrose)
* [ ] Test clicker (@visnup)
* [ ] Get there in the morning and have a co-working sesh (@visnup)
