### ISSUE TITLE
Checklist: Week of Dec 7

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#96]
### Speakers & Performers
* [ ] Lock in 3 out of 4 speakers
  * [ ] Reach out to Nicole (@visnup)
  * [x] Reach out to Jacky (@billyroh)
  * [ ] Find more creative talks (everyone)
* [ ] Lock in 1 out of 2 performers
  * [x] Reach out to Sahana (@visnup)
* [ ] More background cafe-like performances (like Evan) (Myles)
* [ ] Ask karaoke-ers to pick shorter, more recognizable songs (@visnup)
* [ ] Reminder to use large high-contrast font for code slides (@visnup)
* [ ] Email TechShop and have them pin up the call for speakers on their community board (@kellyk)
* [ ] Find robotics speakers (@emilyrose)
* [ ] Get alterconf/TechInclusion past speakers (@kellyk)

### Sales & Promotion
* [ ] wafflejs.com/student – photos, student testimonials, promotional stuff (@billyroh)
* [ ] Ask coding schools and universities to help us promote (@kellyk)
* [x] Ship the new version of the website (@visnup + @billyroh)
* [x] Get feedback on the idea of a speaker+sponsor brunch to speakers (@visnup + everyone)
* [x] Create a page for speaker lunch event (@billyroh)
  * [x] Ask for feedback from speakers, sponsors (@billyroh)

### Equipment
* [ ] Get quieter table games (Pictionary?) (@visnup)
* [ ] Order more butcher paper (@visnup)
* [ ] Get scissors (@visnup)
* [ ] Get more sharpies
* [x] WMO stickers
* [ ] Butcher paper
* [ ] Name tags?
* [ ] Get tupperware container for stickers
* [ ] Get more Opendoor stickers
* [ ] Test lapel mic with a PA (@visnup, Brian)
* [x] Ask venue people if they have storage options (@billyroh)
  * [ ] Or, get a bigger carrying case (@visnup)
* [ ] How does new PA interconnect the speakers? Get a cable long enough (@visnup?)
  * [ ] 2x Stereo RCA → 1/4" cables, short (mixer-to-DAC interconnect, mixer-to-barn-soundsystem interconnect) (@visnup)
  * [ ] Power cable for PA long enough to have the PA and projector connect to the same extension cable (@visnup)
* [ ] Short XLR cables for wireless mic receiver to mixer connections (@visnup)

### Odds & Ends
* [ ] Order a few plain waffles (@billyroh)
* [ ] Visualize repeat attendance (gauge loyalty) (@visnup)
* [ ] Edit host notes for essentials (@visnup, @emilyrose)
* [ ] Tweak short code of conduct for brevity (@visnup, @emilyrose)

**Comment by billyroh** [comment]
:point_right: https://github.com/wafflejs/wafflejs.github.io/issues/96
